### ISSUE TITLE
字幕下载出错

### ISSUE THREAD

**Issue by Hiccup6** [91270/MeiamSubtitles#25]
The ssl connection could not be established。
怎么办？

**Comment by kingjoydom** [comment]
一样的问题，没有人回复吗？

**Comment by CNdaxigua** [comment]
Centos7遇到的

**Comment by 91270** [comment]
已修复，请测试

**Comment by louis000008** [comment]
EMBY 处理请求时发生错误。请稍后尝试。 需要怎么做

**Comment by 91270** [comment]
> EMBY 处理请求时发生错误。请稍后尝试。 需要怎么做

那个插件下载时候的报错

**Comment by CNdaxigua** [comment]
可以了，一切正常

**Comment by louis000008** [comment]
> 

MeiamSub.Thunder的  下载黑客帝国字幕  点下载就跳出来请求时发生错误      日志里显示NO FOUND 
Format : srt - Rate :

**Comment by 91270** [comment]
> > 
> 
> MeiamSub.Thunder的 下载黑客帝国字幕 点下载就跳出来请求时发生错误 日志里显示NO FOUND 是因为没有这个字幕？ [MEIAMSUB] The.Matrix.Resurrections.2021.2160p.HMAX.WEB-DL.DDP5.1.Atmos.HDR.H.265.mkv | zh-CN | 迅雷 MeiamSub.Thunder Format : srt - Rate :

我看了一下迅雷返回的是 404 错误

**Comment by CNdaxigua** [comment]
> > 
> 
> MeiamSub.Thunder的 下载黑客帝国字幕 点下载就跳出来请求时发生错误 日志里显示NO FOUND 是因为没有这个字幕？ [MEIAMSUB] The.Matrix.Resurrections.2021.2160p.HMAX.WEB-DL.DDP5.1.Atmos.HDR.H.265.mkv | zh-CN | 迅雷 MeiamSub.Thunder Format : srt - Rate :
你可以试试射手插件搜索字幕或者emby自带的开源字幕插件
