### ISSUE TITLE
大佬，希望能支持字幕库，实测比opensubtitles字幕丰富

### ISSUE THREAD

**Issue by wisinfun** [91270/MeiamSubtitles#26]
https://zmk.pw/
https://zimuku.org/

**Comment by x91270** [comment]
这两个不支持 HASH 匹配字幕

**Comment by wisinfun** [comment]
> 

https://github.com/pizzamx/zimuku_for_kodi
这个插件有参考键值不，不太懂开发，哈哈

**Comment by wisinfun** [comment]
> 这两个不支持 HASH 匹配字幕

https://github.com/pizzamx/zimuku_for_kodi
这个插件有参考键值不，不太懂开发，哈哈

**Comment by 91270** [comment]
这两个站点。不是通过文件 HASH 精确匹配的，之前考虑过，但是他是根据名字进行匹配的，同一个片子。不同的码率，可能时间轴不一样，所以字幕容易对不上，有其他类似的程序可以获取字幕。所以没有开发
