### ISSUE TITLE
插件搜索任何影片都提示无结果

### ISSUE THREAD

**Issue by Tigheliu** [91270/MeiamSubtitles#36]
<img width="1061" alt="image" src="https://user-images.githubusercontent.com/5736058/161559649-d4263c6a-fa9d-4c26-89b5-13470a747cd3.png">
<img width="904" alt="image" src="https://user-images.githubusercontent.com/5736058/161559855-efb36512-3e27-4beb-bc63-0a7a132e8309.png">

请教一下作者，您这个插件安装上去之后，搜索任何的电影都是无结果

**Comment by gzxiexl** [comment]
我也是 出现什么问题啊？已经更新最新的1.0.5版本了

**Comment by 91270** [comment]
可能是片源的问题，没有对应的字幕，你再试下别的影片

**Comment by Tigheliu** [comment]
我试了很多热门片源 opensubtitle都有，射手也有

**Comment by baiguke2019** [comment]
> 可能是片源的问题，没有对应的字幕，你再试下别的影片

版本：4.7.0.30 测试版      这个版本不能用吗？  同是‘’未找到结果‘’

**Comment by lqdmz** [comment]
> 可能是片源的问题，没有对应的字幕，你再试下别的影片
用了最新版的，也是“未找到结果”
安装在LUNIX上
