### ISSUE TITLE
群晖没有该目录 /var/packages/EmbyServer/target/var/plugins

### ISSUE THREAD

**Issue by unyielding2013** [91270/MeiamSubtitles#44]
群晖没有该目录 /var/packages/EmbyServer/target/var/plugins
只有/var/packages/EmbyServer/var/plugins

**Comment by shelken** [comment]
使用共享文件夹挂载Emby目录，设置权限为自己可以看到
![5Cy8sD4ij7AG6Ew](https://s2.loli.net/2022/05/29/5Cy8sD4ij7AG6Ew.png)
