### ISSUE TITLE
插件无法安装

### ISSUE THREAD

**Issue by soul3201** [91270/MeiamSubtitles#47]
我的emby 4.7.1.0 最新插件1.0.8.0 两个文件都放文件夹里了 但是重启服务后插件未安装 不知道是不是位置不对呢？
<img width="1053" alt="WX20220605-112835@2x" src="https://user-images.githubusercontent.com/80696655/172033743-a99fd02e-1761-4ab1-89d9-af2aac81d77a.png">
<img width="2559" alt="WX20220605-112931@2x" src="https://user-images.githubusercontent.com/80696655/172033765-e07b994d-c56d-4557-b45f-af28db9dbc81.png">

**Comment by beck917** [comment]
-rw-r--r-- 1 emby emby  33792 Jun  5 15:03 Emby.MeiamSub.Shooter.dll
-rw-r--r-- 1 emby emby  33280 Jun  5 15:03 Emby.MeiamSub.Thunder.dll

修改权限

**Comment by LuckyPuppy514** [comment]
查找插件安装位置，可以执行（自行判断目录是否正确，可以看里面是否有已经安装的插件）：
```
find / -name plugins
```

查询文件权限，执行：
```
ls -l
```
把文件权限修改为与已经安装插件一样的权限，比如：
```
chmod 755 *MeiamSub*.dll
```
或全给：
```
chmod 777 *MeiamSub*.dll
```

**Comment by wangshuai-007** [comment]
我的版本是群晖 4.7.2套件版
我现在遇到一样的问题
![image](https://user-images.githubusercontent.com/17959236/175754568-bf3da029-e89e-480c-ba45-0c41052aefa0.png)

我已经复制好了也给了权限了,但是插件中心还是看不到
现在是不支持还是什么原因?能在哪里看到日志吗?
