### ISSUE TITLE
EMBY使用一直不停自动下载字幕的问题

### ISSUE THREAD

**Issue by BenBenJian** [91270/MeiamSubtitles#51]
一直在不停自动下载字幕，很多电影自动下载了十几个字幕了，怎么处理？
谢谢

**Comment by bjzhili** [comment]
请问docke版的emby如何安装这个插件

**Comment by yswtrue** [comment]
好像我也有这个问题

**Comment by yswtrue** [comment]
> 请问docke版的emby如何安装这个插件

可以设置volumes
```
  12   │     volumes:
  13   │       - ./config:/config # Configuration directory

```
然后把下载的dll文件放到config/plugins/下，重启emby就可以了

**Comment by 91270** [comment]
https://github.com/91270/MeiamSubtitles/issues/28#issue-1088377564
