### ISSUE TITLE
单个非常好用，但是请问我该如何一键下载整剧字幕

### ISSUE THREAD

**Issue by Max66888** [91270/MeiamSubtitles#54]
如题，我无法找到入口以便我可以一键下载全剧字幕，只能一个一个的搜索并且速度很慢，我使用tmm刮削器，在媒体库设置不启用任何刮削器，只勾选两个字幕插件，无法自动下载全部

**Comment by 91270** [comment]
Emby 的机制是，勾选插件 等同于 启动自动匹配下载， 不勾选 等同于 手动查找下载 ， 他没有提供 整个 剧集的手动下载功能
