### ISSUE TITLE
每次扫描媒体都会自动下载字幕，造成目录下面一堆重复字幕，即使关掉自动计划任务的download subtitle也不行

### ISSUE THREAD

**Issue by renoshi** [91270/MeiamSubtitles#61]
每次扫描媒体都会自动下载字幕，造成目录下面一堆重复字幕，即使关掉自动计划任务的download subtitle也不行，类似下图情况
![image](https://user-images.githubusercontent.com/6801781/185019003-933a82a4-5a4f-4fe8-8096-6c72f3134e78.png)

**Comment by gamesbain** [comment]
我也有这个问题.所以只能删了插件...

**Comment by alanljj** [comment]
这个问题似乎还是存在，请问有什么方法避免吗

**Comment by alanljj** [comment]
看了一下重复的文件都是没获取成功产生的，大小在300字节左右，可以用命令先列出来看一下
find /volume1/video/film -size -500c -size +200c -type f -name "*.srt" -exec ls -ld {} \;

然后直接删除，也可以添加一个计划任务吧
find /volume1/video/film -size -500c -size +200c -type f -name "*.srt" -exec rm -f {} \;

还是期待大神更新一下源代码，彻底解决问题。

**Comment by 91270** [comment]
重复文件发一个看下

**Comment by nicedavid0629** [comment]
> 重复文件发一个看下

[A.Dog's.Journey.2019.BluRay.1080p.TrueHD.7.1.x264-MTeam.30.zh-cn.zip](https://github.com/91270/MeiamSubtitles/files/9893306/A.Dog.s.Journey.2019.BluRay.1080p.TrueHD.7.1.x264-MTeam.30.zh-cn.zip)
大佬你好, 我在今年5月也遇到了同样的问题, 后来停止了计划任务没有再发现这个情况了, 目前不敢使用计划任务. 希望附件中的文件可以协助你调试, 谢谢

**Comment by nicedavid0629** [comment]
> > 重复文件发一个看下
> 
> [A.Dog's.Journey.2019.BluRay.1080p.TrueHD.7.1.x264-MTeam.30.zh-cn.zip](https://github.com/91270/MeiamSubtitles/files/9893306/A.Dog.s.Journey.2019.BluRay.1080p.TrueHD.7.1.x264-MTeam.30.zh-cn.zip) 大佬你好, 我在今年5月也遇到了同样的问题, 后来停止了计划任务没有再发现这个情况了, 目前不敢使用计划任务. 希望附件中的文件可以协助你调试, 谢谢

版本信息: 
Emby: 4.6.3.0
MeiamSubtitles: 1.0.6.0

**Comment by nicedavid0629** [comment]
> > 重复文件发一个看下
> 
> [A.Dog's.Journey.2019.BluRay.1080p.TrueHD.7.1.x264-MTeam.30.zh-cn.zip](https://github.com/91270/MeiamSubtitles/files/9893306/A.Dog.s.Journey.2019.BluRay.1080p.TrueHD.7.1.x264-MTeam.30.zh-cn.zip) 大佬你好, 我在今年5月也遇到了同样的问题, 后来停止了计划任务没有再发现这个情况了, 目前不敢使用计划任务. 希望附件中的文件可以协助你调试, 谢谢

版本信息: 
Emby: 4.6.3.0
MeiamSubtitles: 1.0.6.0

**Comment by 91270** [comment]
你取消勾选插件

**Comment by 108star** [comment]
媒体库里取消勾选后就可以避免自动下载字幕

**Comment by xingfanxia** [comment]
关闭自动下载字幕怎么手动下载呢
