### ISSUE TITLE
射手是不是挂了

### ISSUE THREAD

**Issue by Wangsc1** [91270/MeiamSubtitles#63]
自动下载和手动下载都不行
![AC8412FA-8C98-4E37-81ED-C3DC4A697374](https://user-images.githubusercontent.com/26079238/195270812-07b67272-635f-4ebd-9fa5-2e7af7ca7eb7.png)
![689594EB-F352-4BBF-8CBA-8D2CA3709C04](https://user-images.githubusercontent.com/26079238/195270821-436c631d-d104-4cc5-9641-cddc7e4b8422.png)

**Comment by 91270** [comment]
NOT FOUND 应该是射手字幕返回了 字幕下载地址，但是该地址无法下载字幕文件
