### ISSUE TITLE
请求增加字幕库(zimuku.org)的适配

### ISSUE THREAD

**Issue by bai0012** [91270/MeiamSubtitles#64]
字幕库网站上的字幕比较多，能不能也做进插件里啊？

**Comment by hypnoSpirax** [comment]
是啊，射手，迅雷影音很多基本没有
这两个基本都全包含了
https://subhd.tv/
https://zmk.pw/

**Comment by 91270** [comment]
这些不是 HASH 匹配的，并且已经有字幕插件了
