### ISSUE TITLE
希望支持一下jellyfin的插件存储库

### ISSUE THREAD

**Issue by shanyan-wcx** [91270/MeiamSubtitles#65]
这样自动更新了。

**Comment by 91270** [comment]
不太明白你的需求，你的意思是发布官方源么

**Comment by shanyan-wcx** [comment]
就是生成一个manifest.json的链接，用户添加到jellyfin里，就能在目录里看到对应的插件

**Comment by 91270** [comment]
有 meta.json 这个文件啊， 在插件中心也可以看的到插件版本

**Comment by 91270** [comment]
![image](https://user-images.githubusercontent.com/61639203/218684188-e1012ba1-397b-48ba-9947-d49069c75d7a.png)

你指的是这个么

**Comment by shanyan-wcx** [comment]
> ![image](https://user-images.githubusercontent.com/61639203/218684188-e1012ba1-397b-48ba-9947-d49069c75d7a.png)
> 
> 你指的是这个么

就是这个

**Comment by 91270** [comment]
好的。我研究一下，随后支持一下

**Comment by lithiumleeow** [comment]
> 好的。我研究一下，随后支持一下

坐等

**Comment by shanyan-wcx** [comment]
可以用了。
