### ISSUE TITLE
jellyfin下载时显示字幕源文件名

### ISSUE THREAD

**Issue by serenity666** [91270/MeiamSubtitles#66]
现在搜索返回的结果都是视频文件名，建议直接显示字幕文件名，像opensubtitle插件一样，这样可以在下载时可以判断字幕合不合适，多条字幕也方便选择。
![Screenshot_2023-02-18-01-11-11-903_org jellyfin mobile](https://user-images.githubusercontent.com/64485323/219720044-26dc4923-ec53-4a1a-924f-9e381152f89f.jpg)

**Comment by 91270** [comment]
字幕网站不返回源文件名
