### ISSUE TITLE
请问docker搭建的emby应该怎么添加？

### ISSUE THREAD

**Issue by twtmactt** [91270/MeiamSubtitles#68]
我是把两个文件添加到映射目录的plugins中，从插件中心也能够看到这两个，但是每次下载字幕的时候总是显示失败，是不是哪里操作不对？望指教

**Comment by 91270** [comment]
下载字幕失败。可能是字幕文件下载链接错误的问题，具体看下日志，是不是访问下载链接时候返回 404 错误
