### ISSUE TITLE
求助：群晖套件不知道在哪个目录

### ISSUE THREAD

**Issue by mazda1152** [91270/MeiamSubtitles#7]

**Comment by moonriseo** [comment]
没安装套件版 可以参考下Docker版 > /docker/emby/config/plugins

**Comment by BENBENBAI** [comment]
我也是，同套件版emby没到目录，请大手子指点。

**Comment by BENBENBAI** [comment]
> > 我也是，同套件版emby没到目录，请大手子指点。
> > /var/packages/EmbyServer/target/var/plugins

上边大佬给指点的位置差不多了，区别是我的实际在 /var/packages/EmbyServer/target/system/plugins

**Comment by 91270** [comment]
应该就是在 plugins 目录。你可以尝一下

**Comment by maojoey** [comment]
/var/packages/EmbyServer/target/var/plugins
/var/packages/EmbyServer/target/system/plugins
我放在这两个目录了，重启后可以正确显示

**Comment by szcorsair** [comment]
有这个目录：/var/packages/EmbyServer/target/system/plugins
这个目录找不到：/var/packages/EmbyServer/target/var/plugins
复制进第一个目录后，重启后没用

**Comment by wisinfun** [comment]
> 有这个目录：/var/packages/EmbyServer/target/system/plugins
> 这个目录找不到：/var/packages/EmbyServer/target/var/plugins
> 复制进第一个目录后，重启后没用

跟你一样的情况 你解决了吗

**Comment by wisinfun** [comment]
已解决，参考这篇文章
https://www.jianshu.com/p/3cae571ea8e5

**Comment by kzcy** [comment]
群晖docker安装emby，怎么复制进容器内？
