### ISSUE TITLE
迅雷下载下来字幕有问题

### ISSUE THREAD

**Issue by mbajiu** [91270/MeiamSubtitles#71]
### **<?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>NoSuchKey</Code>
  <Message>The specified key does not exist.</Message>
  <RequestId>645F5BA4359F9A313158843B</RequestId>
  <HostId>xlppc-subtitle.oss-cn-shanghai-internal.aliyuncs.com</HostId>
  <Key>DC/47/DC47896C27412CBC3713A905DD43EDE843B310C4.srt</Key>
  <EC>0026-00000001</EC>
</Error>**
# # @91270

**Comment by mbajiu** [comment]
![屏幕截图 2023-05-13 174321](https://github.com/91270/MeiamSubtitles/assets/63810600/e9acc776-3c79-4143-acfc-b63ffbc80ff6)

**Comment by 91270** [comment]
字母源的问题
