### ISSUE TITLE
emby 迅雷插件能搜索到字幕但无法世纪访问内容，导致下载大量重复空白字幕文件

### ISSUE THREAD

**Issue by JoeMartini** [91270/MeiamSubtitles#75]
版本：1.0.8.0
emby 后台持续报错
搜索字幕预览时提示
NoSuchKey
The specified key does not exist.
65312C448252DD3830241B4A
xlppc-subtitle.oss-cn-shanghai-internal.aliyuncs.com
E7/12/E712A905DBC671AAB58F27042BF0C054EFC679F0.srt
0026-00000001
https://api.aliyun.com/troubleshoot?q=0026-00000001
![IMG_1506](https://github.com/91270/MeiamSubtitles/assets/7817831/47e4c153-0f39-4ce8-a9ce-5455fbebe19a)
![IMG_1505](https://github.com/91270/MeiamSubtitles/assets/7817831/e6d123ad-e50b-4ae5-9b65-b1c4ecea4bae)

**Comment by ZIZNAH** [comment]
貌似是迅雷改了接口

**Comment by iovejieba** [comment]
貌似确实是改了接口地址  不知道作者会不会更新！

**Comment by 91270** [comment]
这个不是改接口了。是迅雷使用的 OSS 云存储有问题了，要么就是没这个文件

**Comment by ayellowcat** [comment]
这个问题在最新版依然存在，作者应该判断下载的响应结果，非200响应就不要存这个文件了，现在存了大量阿里云的无效文件

**Comment by 91270** [comment]
有返回响应内容么？

**Comment by ayellowcat** [comment]
> 有返回响应内容么？

因为那些文件我删除了，没有保留，不过我以前使用过阿里云oss，他们文件不存在时，会返回404响应码，并且响应体是xml，返回类似于以下内容
`<Error>
<script/>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<RequestId>671DA35F57201732316FF893</RequestId>
<HostId>XXXX.oss-cn-beijing.aliyuncs.com</HostId>
<Key>XXXXX</Key>
<EC>0026-00000001</EC>
<RecommendDoc>https://api.aliyun.com/troubleshoot?q=0026-00000001</RecommendDoc>
</Error>`
