### ISSUE TITLE
emby 4.8.8.0搜不到字幕

### ISSUE THREAD

**Issue by UCHIHAHA103** [91270/MeiamSubtitles#85]
字幕插件用的是最新的v1.0.10.0，放入emby插件目录后，显示加载了插件，但是在播放界面依然搜不到字幕，插件不生效
![image](https://github.com/91270/MeiamSubtitles/assets/61904674/5df525e5-202e-49a5-b4d8-ebe791cf33c7)

![image](https://github.com/91270/MeiamSubtitles/assets/61904674/58b4ad8b-bca3-4045-8a25-842f20229357)

**Comment by 91270** [comment]
HASH 匹配，压制格式不同，不代表都可以匹配到字母，
