### ISSUE TITLE
字幕总是下载太多

### ISSUE THREAD

**Issue by Zachwang007** [91270/MeiamSubtitles#89]
有的电影，字幕下载了几百个，太多字幕文件了。太多了

**Comment by 91270** [comment]
先不勾选插件，试试，回头研究一下问题，从代码层面处理

**Comment by yx365** [comment]
> 有的电影，字幕下载了几百个，太多字幕文件了。太多了

终于找到源头了，一直没注意下了几万个字幕文件了。。。

**Comment by yanggis** [comment]
同样的问题，会自动为一部电影反反复复下载字幕文件，可以下几万个，永不停止。
