### ISSUE TITLE
大佬，EMBY媒体库加载的是strm文件，是不是用不了？

### ISSUE THREAD

**Issue by Wilsonhaha2023** [91270/MeiamSubtitles#93]
如题，我是emby4.8.8.0，放入插件库后也能显示插件，但是字幕搜索结果只有open subtitles搜到的结果。之前直接加载视屏文件的时候是能搜出结果的。所以这是strm的问题，取消hash匹配不知道有没有用？

**Comment by 91270** [comment]
这个插件是需要读取文件 hash 来精确检查字幕的，如果是在线流媒体，是没办法判断 hash 的
